version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: cocash-api
    command: nodemon --watch './**/*.go' --signal SIGTERM --exec 'go' run /usr/src/app/main.go

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf