version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: notes-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - notes-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: notes-api
    command: go build -v ./cmd/apiserver && ./apiserver
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=test21
      - DB_NAME=postgres
      - LOG_LEVEL=debug
    volumes:
      - ./api:/usr/src/app
      - ${GOPATH}/pkg:/go/pkg
    links:
      - db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - notes-network

  nginx:
    image: nginx:stable-alpine
    container_name: notes-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - db
    networks:
      - notes-network

  db:
    image: postgres:14.1-alpine
    container_name: notes-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "test21"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - notes-network

volumes:
  postgres_db:

networks:
  notes-network:
    driver: bridge
