version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        docker_id: ${DOCKER_UID}
        docker_user: ${DOCKER_USER}
    command: air -c .air.toml && migrate

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf